In [33]:
import os
import cv2
import numpy as np

# Local paths to your image folders
folder_path1 = r'G:\Deep Learning in Computer Vision (DMET1067)\Milestone 2\Our Dataset\Our Dataset\Karim Abdelaziz Cropped 2\Karim Training'
folder_path2 = r'G:\Deep Learning in Computer Vision (DMET1067)\Milestone 2\Our Dataset\Our Dataset\Hend Sabry Cropped\Hend Training'
folder_path3 = r'G:\Deep Learning in Computer Vision (DMET1067)\Milestone 2\Our Dataset\Our Dataset\Hany Ramzy Cropped\Hany Training'

# Function to read images from a folder and resize them
def read_images_from_folder(folder_path, label, image_size=(512, 512)):
    images = []
    labels = []

    for filename in os.listdir(folder_path):
        img_path = os.path.join(folder_path, filename)
        img = cv2.imread(img_path)

        if img is not None:
            # Resize image to 512x512x3
            img = cv2.resize(img, image_size)
            images.append(img)
            labels.append(label)

    return images, labels

# Paths to your image folders and labels
folder_paths = [folder_path1, folder_path2, folder_path3]
labels = ["Karim", "Hend", "Hany"]  # Example labels for each folder

# Initialize empty lists to store images and corresponding labels
all_images = []
all_labels = []


for folder_path, label in zip(folder_paths, labels):
    images, label_list = read_images_from_folder(folder_path, label)
    all_images.extend(images)
    all_labels.extend(label_list)

# Convert lists to numpy arrays
all_images = np.array(all_images)
all_labels = np.array(all_labels)

# Save the images and labels arrays to numpy files
np.save("images.npy", all_images)
np.save("labels.npy", all_labels)

print("Images and labels saved successfully!")


Images and labels saved successfully!


In [34]:
print(all_images[800])
print(all_labels[800])

[[[ 46  84 126]
  [ 46  84 126]
  [ 46  84 126]
  ...
  [142 168 182]
  [145 171 185]
  [146 172 186]]

 [[ 46  84 126]
  [ 46  84 126]
  [ 46  84 126]
  ...
  [142 168 182]
  [145 171 185]
  [146 172 186]]

 [[ 46  84 126]
  [ 46  84 126]
  [ 46  84 126]
  ...
  [142 168 182]
  [144 170 184]
  [145 171 185]]

 ...

 [[105 120 123]
  [105 120 123]
  [106 121 124]
  ...
  [ 67  84  93]
  [ 66  83  92]
  [ 66  83  92]]

 [[105 120 123]
  [105 120 123]
  [106 121 124]
  ...
  [ 67  84  93]
  [ 67  84  93]
  [ 67  84  93]]

 [[105 120 123]
  [105 120 123]
  [106 121 124]
  ...
  [ 68  85  94]
  [ 67  84  93]
  [ 67  84  93]]]
Hany


# Convo Layer

In [2]:
import numpy as np

class ConvLayer:
    def __init__(self, num_filters, filter_size, filter_weights=None):
        self.num_filters = num_filters
        self.filter_size = filter_size

        if filter_weights is None:
            # Initialize random filter weights
            self.filters = np.random.randn(num_filters, *filter_size) / (filter_size[0] * filter_size[1])
        else:
            # Use predefined filter weights
            
            self.filters = filter_weights

    @classmethod
    def from_filters(cls, filters):
        """
        Initialize the ConvLayer with predefined filter weights.

        :param filters: Predefined filters (num_filters, height, width, channels).
        """
        num_filters, height, width, channels = filters.shape
        conv_layer = cls(num_filters, (height, width, channels))
        conv_layer.filters = filters
        return conv_layer
    def iterate_filters(self, input_data):
        """
        Iterate over filters and apply them to the input data.

        :param input_data: Input data (batch_size, height, width, channels).
        :return: Convolved output.
        """
        batch_size, height, width, channels = input_data.shape

        # Iterate over each filter
        for f in range(self.num_filters):
            filter_height, filter_width, filter_channels = self.filters[f].shape
             # Initialize output array
            conv_output = np.zeros((batch_size, height - filter_height + 1, width - filter_width + 1, self.num_filters))
            for h in range(height - filter_height + 1):
                for w in range(width - filter_width + 1):
                    # Extract patch from input data
                    patch = input_data[:, h:h + filter_height, w:w + filter_width, :filter_channels]

                    # Apply filter
                    conv_output[:, h, w, f] = np.sum(patch * self.filters[f], axis=(1, 2, 3))

        return conv_output
    

    def forward(self, input_data):
        """
        Perform forward pass for convolutional layer.

        :param input_data: Input data (batch_size, height, width, channels).
        :return: Output data after convolution.
        """
        return self.iterate_filters(input_data)


# Predefined filters
filters = np.array([
    [[[1, 1, 1], [1, 1, 1], [1, 1, 1]],
     [[1, 1, 1], [1, 1, 1], [1, 1, 1]],
     [[1, 1, 1], [1, 1, 1], [1, 1, 1]]],  

    [[[0, 0, 0], [0, 1, 0], [0, 0, 0]],
     [[0, 0, 0], [0, 1, 0], [0, 0, 0]],
     [[0, 0, 0], [0, 1, 0], [0, 0, 0]]],  

    [[[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]],
     [[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]],
     [[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]]],  

    [[[-1, -2, -1], [0, 0, 0], [1, 2, 1]],
     [[-1, -2, -1], [0, 0, 0], [1, 2, 1]],
     [[-1, -2, -1], [0, 0, 0], [1, 2, 1]]], 

    [[[0, -1, 0], [-1, 5, -1], [0, -1, 0]],
     [[0, -1, 0], [-1, 5, -1], [0, -1, 0]],
     [[0, -1, 0], [-1, 5, -1], [0, -1, 0]]]   
])







# Pooling

In [3]:
import numpy as np

class PoolingLayer:
    def __init__(self, pool_size=(2, 2), pool_type='MAX'):
        """
        Initialize the PoolingLayer with the given pool size and type.

        :param pool_size: Size of the pooling filter (height, width).
        :param pool_type: Pooling type ('MAX' or 'AVG').
        """
        self.pool_size = pool_size
        self.pool_type = pool_type

    def forward(self, input_data):
        """
        Perform forward pass for pooling layer.

        :param input_data: Input data (batch_size, height, width, channels).
        :return: Output data after pooling.
        """
        batch_size, height, width, channels = input_data.shape
        pool_height, pool_width = self.pool_size

        # Calculate output dimensions
        out_height = height // pool_height
        out_width = width // pool_width

        # Initialize output array
        output_data = np.zeros((batch_size, out_height, out_width, channels))

        for b in range(batch_size):
            for h in range(out_height):
                for w in range(out_width):
                    for c in range(channels):
                        h_start = h * pool_height
                        h_end = h_start + pool_height
                        w_start = w * pool_width
                        w_end = w_start + pool_width

                        # Extract a patch from the input data
                        patch = input_data[b, h_start:h_end, w_start:w_end, c]

                        # Perform pooling
                        if self.pool_type == 'MAX':
                            output_data[b, h, w, c] = np.max(patch)
                        elif self.pool_type == 'AVG':
                            output_data[b, h, w, c] = np.mean(patch)

        return output_data


# Activation

In [4]:
def activation_function(Z):
    """
    Simple activation function A(Z) = Z if Z >= 0, else A(Z) = 0.

    :param Z: Input data.
    :return: Activated output.
    """
    return np.maximum(0, Z)



# Conv Block

In [5]:

# Define the Convolution block
class ConvBlock:
    def __init__(self, num_filters, filter_size=(3, 3, 3), pool_size=(2, 2)):
        """
        Initialize the ConvBlock.

        :param num_filters: Number of filters.
        :param filter_size: Size of the filters (height, width, channels). Default is (3, 3, 3).
        :param pool_size: Size of the pooling filter (height, width). Default is (2, 2).
        """
        self.conv_layer = ConvLayer(num_filters, filter_size)
        self.pool_layer = PoolingLayer(pool_size)

    def forward(self, input_data):
        """
        Perform forward pass for the ConvBlock.

        :param input_data: Input data (batch_size, height, width, channels).
        :return: Output data after convolution and pooling.
        """
        conv_output = self.conv_layer.forward(input_data)
        pool_output = self.pool_layer.forward(conv_output)
        return pool_output


# Define the Flattening layer
class FlattenLayer:
    def forward(self, input_data):
        """
        Flatten the input data.

        :param input_data: Input data (batch_size, height, width, channels).
        :return: Flattened data.
        """
        batch_size = input_data.shape[0]
        return input_data.reshape(batch_size, -1)


# Create the network
class SimpleCNN:
    def __init__(self):
        """
        Initialize the SimpleCNN network.
        """
        self.conv_block1 = ConvBlock(5)  # Filter size is (3, 3, 3)
        self.conv_block2 = ConvBlock(5)  # Filter size is (3, 3, 3)
        self.conv_block3 = ConvBlock(5)  # Filter size is (3, 3, 3)
        self.flatten_layer = FlattenLayer()

    def forward(self, input_data):
        """
        Perform forward pass for the SimpleCNN network.

        :param input_data: Input data (batch_size, height, width, channels).
        :return: Output data after passing through the network.
        """
        # Convolution block 1
        conv1_output = self.conv_block1.forward(input_data)

        # Convolution block 2
        conv2_output = self.conv_block2.forward(conv1_output)

        # Convolution block 3
        conv3_output = self.conv_block3.forward(conv2_output)

        # Flatten
        flattened_output = self.flatten_layer.forward(conv3_output)

        # Downsampling to size 1x128 
        downsampled_output = flattened_output[:, :128]

        return downsampled_output



# Testing

In [6]:
import os
import cv2
import numpy as np

folder_path1 = r'G:\Deep Learning in Computer Vision (DMET1067)\Milestone 2\Our Dataset\Our Dataset\Karim Abdelaziz Cropped 2\KarimTraining'
folder_path2 = r'G:\Deep Learning in Computer Vision (DMET1067)\Milestone 2\Our Dataset\Our Dataset\Hend Sabry Cropped\HendTraining'
folder_path3 = r'G:\Deep Learning in Computer Vision (DMET1067)\Milestone 2\Our Dataset\Our Dataset\Hany Ramzy Cropped\HanyTraining'

# Function to read images and resize them
def read_images_from_folder(folder_path, label, image_size=(512, 512)):
    images = []
    labels = []

    for filename in os.listdir(folder_path):
        img_path = os.path.join(folder_path, filename)
        img = cv2.imread(img_path)

        if img is not None:
            img = cv2.resize(img, image_size)
            images.append(img)
            labels.append(label)

    return images, labels

# Paths to your image folders and labels
folder_paths = [folder_path1, folder_path2, folder_path3]
labels = ["Karim", "Hend", "Hany"]  

# Initialize empty lists to store images and corresponding labels
test_images = []
test_true_labels = []

# Read images from each folder and store them in all_images list
for folder_path, label in zip(folder_paths, labels):
    images, label_list = read_images_from_folder(folder_path, label)
    test_images.extend(images)
    test_true_labels.extend(label_list)

# Convert lists to numpy arrays
test_images = np.array(test_images)
test_true_labels = np.array(test_true_labels)

# Save the images and labels arrays to numpy files
np.save("test_images.npy", test_images)
np.save("test_true_labels.npy", test_true_labels)

print("Images and labels saved successfully!")


Images and labels saved successfully!


In [7]:
import numpy as np
from sklearn.cluster import KMeans
from sklearn.metrics import accuracy_score



# Load the test images and true labels
test_images = np.load("test_images.npy")
test_true_labels = np.load("test_true_labels.npy")


# Initialize the SimpleCNN network
simple_cnn = SimpleCNN()




# Forward pass through the CNN to get features
def extract_features(model, images, true_labels):
    features = []
    labeled_features = []  
    
    for image, label in zip(images, true_labels):
        output = model.forward(image[np.newaxis, :, :, :])
        flattened_output = output.flatten()
        
        features.append(flattened_output)
        labeled_features.append((flattened_output, label))
        
    return np.array(features), labeled_features

# Extract features and labeled features from test images
features, labeled_features = extract_features(simple_cnn, test_images, test_true_labels)



In [ ]:
num_classes = 3
kmeans = KMeans(n_clusters=num_classes)
kmeans.fit(features)


# Get the labels (clusters) assigned by k-means
predicted_labels = kmeans.labels_

In [ ]:
from collections import defaultdict, Counter


# Create a dictionary to store cluster information
cluster_info = defaultdict(list)

# Populate cluster_info with original labels for each cluster
for i, cluster_label in enumerate(predicted_labels):
    original_label = labeled_features[i][1]  
    cluster_info[cluster_label].append(original_label)

# Count the number of features mapped to each label within each cluster
label_distribution_in_clusters = defaultdict(lambda: defaultdict(int))
for cluster_label, labels in cluster_info.items():
    total_features = len(labels)
    label_count = Counter(labels)
    label_distribution_in_clusters[cluster_label] = {label: count for label, count in label_count.items()}
    label_distribution_in_clusters[cluster_label]['total_features'] = total_features



In [11]:
# Create a mapping dictionary to map cluster labels to actor names
unique_labels = np.unique(test_true_labels)
label_map = {i: actor_name for i, actor_name in enumerate(unique_labels)}

# Map cluster labels to actor names for predicted labels
predicted_actor_names = [label_map[label] for label in predicted_labels]

# Calculate accuracy
accuracy = accuracy_score(test_true_labels, predicted_actor_names)
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 44.53%
